### ISSUE TITLE
What are all the patches?

### ISSUE THREAD

**Issue by clonm** [tozd/docker-sympa#6]
Trying to upgrade to 6.2, I'm not sure what most of the patches are supposed to do or if they are still needed with the new version of Sympa. I updated the password default one but what are 3004-cookies.patch, 3005-bulklistname.patch, 3010-mhonarc-ressources.patch, and 3020-include_sources_subscriber.patch and for? Does cloyne's version depend on them?

**Comment by mitar** [comment]
Those are some patches which have been needed for a particular version of Sympa. When updating Sympa to a new version one should check if they are still needed.

* `3004-cookies.patch` fixes the `Cookie_domain(%s) does NOT match HTTP_HOST; setting cookie_domain to` warning when Sympa runs on a subdomain.
* `3005-bulklistname.patch` fixes SQL injection issue.
* `3006-personalize_recipient.patch` is a feature which allows one to have in `To` e-mail of the recipient and not mailing list mail (you still send to the mailing list, but they get it as it was send to only them).
* `3007-no-database-create.patch` generally I run Sympa with database user which does no have permission to create a database (just use it).
* `3010-mhonarc-ressources.patch` in mailing list archives, e-mails can be wrapped as "flowed" and archive does not show them well.
* 3020-include_sources_subscriber.patch` I think relates to Cloyne and was required because we have for `alumni` many source mailing lists and Sympa stores them all as one string, which started hitting the limit of the column length in the database.
